// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function migrateDatabaseUrl(): string {
  const direct = process.env.DATABASE_URL?.trim();
  if (direct?.startsWith("postgres")) {
    return direct;
  }
  return (
    process.env.STORAGE_PRISMA_DATABASE_URL ||
    process.env.STORAGE_POSTGRES_URL ||
    ""
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: migrateDatabaseUrl(),
  },
});
